# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuchhalterAi < Formula
  desc "Automatically sync all your incoming invoices from your suppliers."
  homepage "https://buchhalter.ai/"
  version "0.0.1-alpha"
  license "SSPL-1.0"

  on_macos do
    on_intel do
      url "https://github.com/buchhalter-ai/buchhalter-ai-cli/releases/download/v0.0.1-alpha/buchhalter-ai_Darwin_x86_64.tar.gz"
      sha256 "ffa39829ac7c90aa1874f1346d066ad48f011233f7c6c14f5892de7bbc5aa485"

      def install
        bin.install "buchhalter-ai"
      end
    end
    on_arm do
      url "https://github.com/buchhalter-ai/buchhalter-ai-cli/releases/download/v0.0.1-alpha/buchhalter-ai_Darwin_arm64.tar.gz"
      sha256 "765779953cb167e985186a13e07a55ece53f4c770ee39152ebd42988bdea2e84"

      def install
        bin.install "buchhalter-ai"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buchhalter-ai/buchhalter-ai-cli/releases/download/v0.0.1-alpha/buchhalter-ai_Linux_x86_64.tar.gz"
        sha256 "218d704cd3db6d66f9c609c87b0f9a5489547b7cd1f25db84fbff48c11068b23"

        def install
          bin.install "buchhalter-ai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buchhalter-ai/buchhalter-ai-cli/releases/download/v0.0.1-alpha/buchhalter-ai_Linux_arm64.tar.gz"
        sha256 "7906427ebf59bd915d16a6363ca39570b00f5b836378e5594270c3ac7e4708d2"

        def install
          bin.install "buchhalter-ai"
        end
      end
    end
  end

  test do
    system "#{bin}/buchhalter version"
  end
end
